### PR TITLE
Feature/app builder update

### PR DESCRIPTION
**Pull request by hsaraujo**
Fixes issue #15

### CODE REVIEW

**Comment by R0cket** [comment]
@hsaraujo can you tell me approx when the Platform App Builder form will be updated?  It appears you might be working on it.. just wondering when I should try back.  Thank you

**Comment by hsaraujo** [comment]
Hi @R0cket. I don't know.. I just made changes to the source code. It's up to @SCuvanov now to approve and put it in the project :)

**Comment by R0cket** [comment]
Ok thanks for the quick turn around.
I just failed it - the changes surprised me as I studied based on a guide I got in Fall.

Please LMK if I could ’test’ the form for you.

THanks

**Comment by R0cket** [comment]
Very valuable tool.  Thank you for this guys!!

**Pull request merged**
